# use_frameworks!

platform :ios, '9.0'

target 'LWWebSocket_Example' do
  pod 'LWWebSocket', :path => '../'

  pod 'Masonry'

end


target 'XXKeyboard' do

  pod 'LWWebSocket', :path => '../'
  pod 'LWWebLoader', :path => '../../lwwebloader/'


end
